// packages/ackworkdesk/src/pages/index.tsx
import { useMemo, useState } from 'react'
import { DataTable, exportRows } from 'react-components-lib.eaa'
import type { ColumnSetting, HeaderRightElement } from 'react-components-lib.eaa'
import moduleConfig from '../module.config.json'
import { apiGet, MainPageContainer, MAIN_PAGE_TABLE_HEIGHT } from '@app/common'

type Row = {
  id: number
  arn: string
  bookingLocation: string
  workflowStage: string
  submissionMode: string
  receivedAt: string
  generatedBy: string
  __receivedAtMs: number
}

export default function AcknowledgmentWorkDesk() {
  const [status, setStatus] = useState<'PENDING' | 'REGISTERED' | 'ALL'>('PENDING')

  const statusOptions = [
    { text: 'Pending Registration', value: 'PENDING' },
    { text: 'Registered', value: 'REGISTERED' },
    { text: 'All', value: 'ALL' }
  ]

  const columns: ColumnSetting[] = useMemo(
    () => [
      { column: 'arn', title: 'ARN #', filter: { type: 'text' } },
      { column: 'bookingLocation', title: 'BOOKING LOCATION' },
      { column: 'workflowStage', title: 'WORKFLOW STAGE' },
      { column: 'submissionMode', title: 'SUBMISSION MODE' },
      { column: 'receivedAt', title: 'RECEIVED DATE AND TIME' },
      { column: 'generatedBy', title: 'GENERATED BY' }
    ],
    []
  )

  const server = useMemo(
    () => ({
      debounceMs: 250,
      fetcher: async ({ pageIndex, pageSize, sorting, columnFilters, globalFilter }: any) => {
        const sortBy = sorting?.[0]?.id ?? ''
        const order = sorting?.[0]?.desc ? 'desc' : 'asc'

        const params: any = {
          limit: pageSize,
          skip: pageIndex * pageSize,
          q: globalFilter ?? '',
          sortBy,
          order,
          filters: JSON.stringify(columnFilters ?? []),
          status
        }

        // Hierarchical key for easy invalidation: ['workdesk', <module>, 'ack', <params>]
        const key = [
          'workdesk',
          moduleConfig.moduleName,
          'ack',
          { pageIndex, pageSize, sortBy, order, columnFilters, q: globalFilter ?? '', status }
        ] as const

        const data = await apiGet<{ rows: Row[]; total: number }>({
          endpoint: '/workdesk/search',
          params,
          queryKey: key // ✅ enables caching via ensureQueryData
        })

        return data
      }
    }),
    [status]
  )

  const downloadControls = useMemo(
    () => ({
      fileName: 'ack_work_desk',
      format: 'xlsx' as const,
      showConfigSection: true,
      showBuiltinAll: false,
      showBuiltinSelected: false,
      extraMenuItems: [
        {
          key: 'server-all',
          icon: 'cloud_download',
          label: 'Download ALL from server',
          onClick: async ({ fileName, format }: { fileName: string; format: 'xlsx' | 'csv' }) => {
            const params: any = { limit: 0, skip: 0, status }
            // Non-cached one-off GET (omit queryKey)
            const data = await apiGet<{ rows: Row[]; total: number }>({
              endpoint: '/workdesk/search',
              params
            })
            await exportRows(data.rows, columns, { fileName, format })
          }
        }
      ]
    }),
    [status, columns]
  )

  const headerLeftElements: HeaderRightElement[] = [
    {
      type: 'dropdown',
      width: 220,
      placeholder: 'Pending Registration',
      options: statusOptions,
      value: status,
      clearable: false,
      onChange: (v: string | string[] | null) =>
        setStatus((Array.isArray(v) ? (v[0] ?? '') : (v ?? '')) as any)
    },
    {
      type: 'button',
      text: 'Registration',
      color: 'success',
      icon: 'plus-circle',
      onClick: () => console.log('Registration')
    }
  ]

  return (
    <MainPageContainer title="Acknowledgment Work Desk">
      <DataTable
        enableGlobalFiltering
        columnSettings={columns}
        enableDownload
        downloadControls={downloadControls}
        serverMode
        server={server as any}
        pageSize={20}
        height={MAIN_PAGE_TABLE_HEIGHT}
        headerLeftElements={headerLeftElements}
      />
    </MainPageContainer>
  )
}
